#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    all_res = []
    for i in range(len(arr)):
        res = sum(arr) - arr[i]
        all_res.append(res)
    print(min(all_res), max(all_res))


if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
